apps/chofer/urls.py
from django.urls import path
from apps.chofer.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = 'index'),
	path('registrar/', RegistrarChofer, name = 'registrar'),
	path('editar/<int:id_chofer>/', EditarChofer, name = 'editar'),
	path('perfil/<int:id_chofer>/', PerfilChofer, name = 'perfil'),
	path('listar/',ListarChofer, name = 'listar'),
	path('trabajar/<int:id_chofer>/', Trabajar, name = 'trabajar'),
	path('gestion/',Gestion, name = 'gestion'),
	path('eliminar/<int:id_chofer>', EliminarChofer, name = 'eliminar'),
	path('suspender/<int:id_chofer>', SuspenderChofer, name = 'suspender'),
	path('habilitar/<int:id_chofer>', HabilitarChofer, name = 'habilitar'),
]

mayaca/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('home/', include('apps.home.urls', namespace = 'home')),
    path('cliente/', include('apps.cliente.urls',namespace = 'cliente')),
    path('administracion/', include('apps.administracion.urls', namespace = 'administracion')),
    path('chofer/', include('apps.chofer.urls', namespace = 'chofer')),
    path('servicio/', include('apps.servicio.urls', namespace = 'servicio')),
    path('accounts/', include ('django.contrib.auth.urls')),
]

apps/chofer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

from datetime import date, datetime


class Chofer(models.Model):
	usuario = models.OneToOneField(User, on_delete = models.CASCADE)
	foto = models.ImageField(upload_to='ChoferFotos/', blank=True)
	cedula = models.CharField(max_length = 8, unique = True)
	telefono = models.CharField(max_length = 12)
	trabajando = models.BooleanField()

	def __str__(self):
		return self.usuario.first_name + ' ' + self.usuario.last_name

class BitacoraChofer(models.Model):
	user = models.ForeignKey(User, on_delete = 'cascade', default = None)
	descripcion = models.CharField(max_length = 12)
	fecha = models.DateField(default = datetime.today)

apps/chofer/forms.py
from apps.chofer.models import * 
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
 

class FormUser(UserCreationForm):
	class Meta:
		model = User
		fields = [
			'username',
			'first_name',
			'last_name',
			'email',
			]
		labels = {
			'username' : 'Nombre de Usuario',
			'first_name': 'Nombre',
			'last_name': 'Apellido' ,
			'email': 'Correo Electronico',
		}
class FormChofer(forms.ModelForm):
	class Meta:
		model = Chofer 
		fields = [
			'cedula',
			'telefono',
			'foto',
		]
		labels = {
			'cedula': 'Cedula',
			'telefono': 'Telefono',
			'foto': 'Foto',
		}

apps/chofer/views.py
from django.shortcuts import render
from apps.chofer.forms import FormChofer
from apps.chofer.models import *
from apps.administracion.forms import FormUser
from apps.administracion.models import Empleado
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login

# Create your views here.

def index(request):
	return render(request, 'chofer/index.html')

 
def EliminarChofer(request,id_chofer):
	usuario_actual = request.user.id 
	empleado = Empleado.objects.filter(usuario = usuario_actual)
	if empleado.exists() == True:
		chofer = Chofer.objects.filter(id = id_chofer)
		if chofer.exists() == True:
			chofer = Chofer.objects.get(id = id_chofer)
			id_user = chofer.usuario_id
			print(id_user)
			usuario = User.objects.get(id = id_user)
			chofer.delete()
			usuario.delete()
			return HttpResponseRedirect(reverse('chofer:listar'))
	return HttpResponseRedirect(reverse('home:index'))

def RegistrarChofer(request):
	if request.method == 'POST':
		user_form = FormUser(request.POST)
		chofer_form = FormChofer(request.POST, request.FILES)
		if user_form.is_valid() and chofer_form.is_valid():
			usuario = user_form.save()
			usuario.refresh_from_db()
			chofer = Chofer(
				usuario = usuario,
				cedula = chofer_form.cleaned_data['cedula'],
				telefono = chofer_form.cleaned_data['telefono'],
				trabajando = True,
				foto = request.FILES['foto']
				)
			chofer.save()
			usuario.is_active = 0
			usuario.save()
			return HttpResponseRedirect(reverse('home:index'))
	else:
		user_form = FormUser
		chofer_form = FormChofer
	return render(request, 'chofer/registro.html', {
		'user_form':user_form,
		'chofer_form':chofer_form
		})
	return HttpResponseRedirect(reverse('home:index'))

def EditarChofer(request, id_chofer):
	if request.user.is_authenticated:
		# Verificar si es empleado
		bandera = False
		usuario_actual = request.user.id 
		empleado = Empleado.objects.filter(usuario = usuario_actual)
		if empleado.exists() == True:
			chofer = Chofer.objects.filter(id = id_chofer)
			if chofer.exists() == True:
				chofer = Chofer.objects.get(id = id_chofer)
				bandera = True
		# Verificar si es el dueño de la cuenta el que intenta acceder
		chofer = Chofer.objects.filter(id = id_chofer)
		if chofer.exists() == True:
			chofer = Chofer.objects.get(id = id_chofer)
			if chofer.usuario_id == usuario_actual:
				bandera = True

	if bandera == True:
		chofer = Chofer.objects.get(id = id_chofer)
		if request.method == 'GET':
			chofer_form = FormChofer(instance = chofer)
			user_form = FormUser(instance = chofer.usuario)
		else:
			chofer_form = FormChofer(request.POST, request.FILES, instance = chofer)
			user_form = FormUser(request.POST, instance = chofer)
			if chofer_form.is_valid() and user_form.is_valid():
				usuario = user_form.save()
				chofer_form.save()
				login(request, usuario)
				return HttpResponseRedirect(reverse('home:index'))
		return render(request, 'chofer/registro.html',{
			'chofer_form': chofer_form,
			'user_form': user_form
			})
	return HttpResponseRedirect(reverse('home:index'))
 
def PerfilChofer(request, id_chofer):
	if request.user.is_authenticated:
		# Verificar si es empleado
		bandera = False
		usuario_actual = request.user.id 
		empleado = Empleado.objects.filter(usuario = usuario_actual)
		if empleado.exists() == True:
			chofer = Chofer.objects.filter(id = id_chofer)
			if chofer.exists() == True:
				chofer = Chofer.objects.get(id = id_chofer)
				bandera = True
		# Verificar si es el dueño de la cuenta el que intenta acceder
		chofer = Chofer.objects.filter(id = id_chofer)
		if chofer.exists() == True:
			chofer = Chofer.objects.get(id = id_chofer)
			if chofer.usuario_id == usuario_actual:
				bandera = True
		if bandera == True:
			return render(request, 'chofer/perfil.html', {'chofer': chofer,'bandera':bandera})
	return render(request, 'chofer/perfil.html')

def ListarChofer(request):
	if request.user.is_authenticated:
		usuario_actual = request.user.id
		empleado = Empleado.objects.filter(usuario_id = usuario_actual)
		if empleado.exists() == True:
			choferes = Chofer.objects.all()
			bandera = True
			return render(request, 'chofer/lista.html', {'choferes':choferes,'bandera':bandera})
	return render(request, 'chofer/lista.html')
		

def Trabajar(request,id_chofer):
	if request.user.is_authenticated:
		# Verificar si es empleado
		bandera = False
		usuario_actual = request.user.id 
		empleado = Empleado.objects.filter(usuario = usuario_actual)
		if empleado.exists() == True:
			chofer = Chofer.objects.filter(id = id_chofer)
			if chofer.exists() == True:
				chofer = Chofer.objects.get(id = id_chofer)
				bandera = True
		# Verificar si es el dueño de la cuenta el que intenta acceder
		chofer = Chofer.objects.filter(id = id_chofer)
		if chofer.exists() == True:
			chofer = Chofer.objects.get(id = id_chofer)
			if chofer.usuario_id == usuario_actual:
				bandera = True
	if bandera == True:
		chofer = Chofer.objects.get(id = id_chofer)
		if chofer.trabajando == True:
			chofer.trabajando = False
		else:
			chofer.trabajando = True
		chofer.save()
		return HttpResponseRedirect('/chofer/perfil/' + str(id_chofer))
	return HttpResponseRedirect(reverse('home:index'))

def Gestion(request):
	return render(request, 'chofer/gestion.html')


def SuspenderChofer(request,id_chofer):
	usuario_actual = request.user.id 
	empleado = Empleado.objects.filter(usuario = usuario_actual)
	if empleado.exists() == True:
		chofer = Chofer.objects.filter(id = id_chofer)
		if chofer.exists() == True:
			chofer = Chofer.objects.get(id = id_chofer)
			usuario = User.objects.get(id = chofer.usuario.id)
			usuario.is_active = 0
			usuario.save()
			return HttpResponseRedirect(reverse('chofer:listar'))
	return HttpResponseRedirect(reverse('home:index'))

def HabilitarChofer(request,id_chofer):
	usuario_actual = request.user.id 
	empleado = Empleado.objects.filter(usuario = usuario_actual)
	if empleado.exists() == True:
		chofer = Chofer.objects.filter(id = id_chofer)
		if chofer.exists() == True:
			chofer = Chofer.objects.get(id = id_chofer)
			usuario = User.objects.get(id = chofer.usuario.id)
			usuario.is_active = 1
			usuario.save()
			return HttpResponseRedirect(reverse('chofer:listar'))
	return HttpResponseRedirect(reverse('home:index'))

templates/chofer/gestion.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    	<div class="row">
    		<div class="col-md-12">
    			<h2>Por desarrollar</h2>
    		</div>
    	</div>
    </div>
{% endblock content %}

templates/chofer/index.html
{% extends 'base.html' %}
{% block chofer %}active{% endblock chofer %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
    		<h1 class="text-center">Pagina principal de chofer</h1>
			<p>Forma parte de nuestra empresa, comienza con hacer tu preregistro y luego te indicaremos los siguientes pasos</p>
			<a href="{% url 'chofer:registrar' %}">Registrate</a>
		</div>
	</div>
</div>
{% endblock content %}

templates/chofer/lista.html
{% extends "base.html" %}
{% block content %}

{% if bandera %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="text-primary text-center">
				Lista de choferes
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<a href="{% url 'chofer:registrar' %}" class="btn btn-primary">Agregar nuevo chofer</a>
			 <table class="table table-hover">
		        <thead>
		          <tr>
		            <th scope="col">#</th>
		            <th scope="col">Usuario</th>
		            <th scope="col">Nombre</th>
		            <th scope="col">Correo Electrónico</th>
		            <th scope="col">Telefono</th>
		            <th scope="col">Estado</th>
		            <th class="text-center">Acciones</th>
		          </tr>
		        </thead>
		        {% if choferes %}
		        <tbody>
		        	    {% for chofer in choferes %}
		      		    <tr>
		      		      <th scope="row"></th>
		      		      <td>{{ chofer.id }}</td>
		      		      <td>{{ chofer.usuario.first_name }}</td>
		      		      <td>{{ chofer.usuario.email }}</td>
		      		      <td>{{ chofer.telefono }}</td>
		      		      <td>
		      		      	{% if chofer.usuario.last_login == Null and chofer.usuario.is_active == 0 %}
		      		      	    <p class="btn btn-danger">Por Revisar</p>
		      		      	{% else %}
								{% if chofer.usuario.is_active == True %}
								    <p class="btn btn-success">Habilitado</p>
								{% else %}
									<p class="btn btn-warning">Suspendido</p>
								{% endif %}
		      		      	{% endif %}
		      		      </td>
		      		      <td>
		      		      <a href="#borrar" data-toggle="modal" class="btn btn-danger" title="Eliminar"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
		      		      <!-- ========== Modal de eliminar =============== -->
							<div class="modal fade" id="borrar">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title">Confirmacion</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
											</button>
										</div>
									<div class="modal-body">
										<p>¿Esta seguro que desea eliminar este chofer?</p>
										<p><strong>Nombre:</strong> {{ chofer.usuario.first_name }} {{ chofer.usuario.last_name }}</p>
									</div>
									<div class="modal-footer">
											<a href="{% url 'chofer:eliminar' chofer.id %}" class="btn btn-primary">Guardar Cambios</a>
											<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
										</div>
									</div>
								</div>
							</div>
		      		      <!-- ========== Fin Modal de eliminar =========== -->
		      		      {% if chofer.usuario.is_active == 0 %}
		                  <a href="#habilitar" data-toggle="modal" class="btn btn-success" title="Habilitar"><i class="fa fa-unlock" aria-hidden="true"></i></a>
		                  <!-- ================ Modal Habilitar =================== -->
							<div class="modal fade" id="habilitar">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title">Habilitar</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<h3 class="text-center text-primary">¿Seguro que desea habilitar al siguiente chofer?</h3>
											<p>Nombre: {{ chofer.usuario.first_name }} {{ chofer.usuario.last_name }}</p>
											<p>Ultima Sesión {{ chofer.usuario.last_login }}</p>
										</div>
										<div class="modal-footer">
											<a href="{% url 'chofer:habilitar' chofer.id %}" class="btn btn-primary">Confirmar</a>
											<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
										</div>
									</div>
								</div>
							</div>
		                  <!-- ================ Fin Modal Habilitar =================== -->
		      		      {% else %}
		      		      <a href="#suspender" data-toggle="modal" class="btn btn-warning" title="Suspender"><i class="fa fa-lock" aria-hidden="true"></i></a>
		      		      <!-- ================ Modal Suspender =================== -->
							<div class="modal fade" id="suspender">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title">Suspender</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<h3 class="text-center text-primary">¿Seguro que desea suspender al siguiente chofer?</h3>
											<p>Nombre: {{ chofer.usuario.first_name }} {{ chofer.usuario.last_name }}</p>
											<p>Ultima Sesión: {{ chofer.usuario.last_login }}</p>
										</div>
										<div class="modal-footer">
											<a href="{% url 'chofer:suspender' chofer.id %}" class="btn btn-primary">Confirmar</a>
											<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
										</div>
									</div>
								</div>
							</div>
		                  <!-- ================ Fin Modal Suspender =================== -->
		      		      {% endif %}
		                  <a href="{% url 'chofer:editar' chofer.id %}" class="btn btn-primary" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
		                  <a href="{% url 'chofer:perfil' chofer.id %}" class="btn btn-info" title="Perfil">Perfil</i></a>
		      		      </td>
		      		    </tr>
		        		{% endfor %}
		        </tbody>
		        {% else %}
	        	    <h1 class="text-primary text-center">No hay registros disponibles</h1>
	        	{% endif %}
		     </table> 
		</div>
	</div>
</div>
{% else %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="text-center text-primary">El enlace al que intenta acceder no esta disponible o no tiene los permisos necesarios para acceder</h2>
			<h1 class="text-center text-primary" style="font-size: 110px;"><i class="fa fa-chain-broken" aria-hidden="true"></i></h1>
		</div>
		<div class="col-md-12">
			<a href="{% url 'home:index' %}" class="btn btn-lg btn-primary" style="display: block">Volver a la pagina principal</a>
		</div>
	</div>
</div>
{% endif %}
{% endblock content %}

templates/chofer/perfil.html
{% extends 'base.html' %}

{% block content %}

{% if bandera == True %}

<div class="container">
	<div class="row">
		<div class="col-md-3">
			<img style="height: 80%; width: 100%; display: block; margin-left: auto; margin-right: auto; border-radius: 10px; margin-bottom: 10px;" src="/static/media/{{ chofer.foto }}" alt="Card image" class="img-responsive">
			<h4>{{ chofer.usuario.first_name }} {{ chofer.usuario.last_name }}</h4>
			<h4 class="text-muted">{{chofer.usuario.username}}</h4>
		</div>
		<div class="col-md-9">
			<h3 class="text-center text-primary">Perfil del Chofer</h3>
			<hr>
			<div class="row">
				<div class="col-md-6 form-control">
					<h4>Viajes Totales</h4>
					<h2 class="text-center text-primary">15</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Viajes Cancelados</h4>
					<h2 class="text-center text-danger">7</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Viajes Realizados</h4>
					<h2 class="text-center text-success">2</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Viajes Pendientes</h4>
					<h2 class="text-center text-warning">6</h2>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">

	<div class="modal fade" id="confirm1">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title">Confirmar</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	      	{% if chofer.trabajando == True %}
	      		<h4>¿Desea estar inhabilitado para trabajar? <i class="fa fa-thumbs-o-down" aria-hidden="true"></i></h4>
	      	{% else %}
	        	<h4>¿Desea estar activo para trabajar? <i class="fa fa-thumbs-o-up" aria-hidden="true"></i></h4>
	      	{% endif %}
	      </div>
	      <div class="modal-footer">
	        <a href="{% url 'chofer:trabajar' chofer.id %}" class="btn btn-primary">Guardar</a>
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
	      </div>
	    </div>
	  </div>
	</div>

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-9">
			<hr>
			<div class="row">
				<div class="col-md-12">
					<h2 class="text-center text-primary" style="margin-bottom: 20px;">Datos del Chofer</h2>
					<div class="row">
						<div class="col-md-6">
							<p><strong>Cedula:</strong> V-{{ chofer.cedula }}</p>
							<p><strong>Nombre:</strong> {{ chofer.usuario.first_name }} {{ chofer.usuario.last_name }}</p>
							<p><strong>Email:</strong> {{ chofer.usuario.email }}</p>
						</div>
						<div class="col-md-6">
							<p><strong>Telefono:</strong> {{ chofer.telefono }}</p>
							{% if chofer.trabajando == True %}
								<p><strong>Trabajando:</strong> Si<a href="#confirm1" data-toggle="modal" class="btn btn-danger btn-sm" style="margin-left: 30px">Cambiar</a></p>
							{% else %}
							   	<p><strong>Trabajando:</strong> No<a href="#confirm1" data-toggle="modal" class="btn btn-success btn-sm" style="margin-left: 30px">Cambiar</a></p>	
							{% endif %}
							<p><strong>Fecha de Ingreso:</strong> {{ chofer.usuario.date_joined }}</p>
						</div>
					</div>
					<p class="text-center">Última Sesión: {{ user.last_login }}</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% else %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="text-center text-primary">El Chofer al que intenta acceder no esta disponible o no tiene los permisos necesarios para acceder</h2>
			<h1 class="text-center text-primary" style="font-size: 110px;"><i class="fa fa-chain-broken" aria-hidden="true"></i></h1>
		</div>
		<div class="col-md-12">
			<a href="{% url 'home:index' %}" class="btn btn-lg btn-primary" style="display: block">Volver a la pagina principal</a>
		</div>
	</div>
</div>
{% endif %}
{% endblock content %}

templates/chofer/registro.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
<div class="container">
	<div class="row">
			<div class="col-md-6">
				{% csrf_token %}
				{{ user_form.as_p }}
			</div>
			<div class="col-md-6">
				{{ chofer_form.as_p }}
				<input type="submit" class="btn btn-primary" value="Registrar">
				<a href="{% url 'home:index' %}" class="btn btn-default">Cancelar</a>
			</div>
	</div>
</div>
</form>
{% endblock content %}