apps/chofer/urls.py
from django.urls import path
from apps.chofer.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = 'index'),
	path('registrar/', RegistrarChofer, name = 'registrar'),
	path('editar/<int:id_chofer>/', EditarChofer, name = 'editar'),
	path('perfil/<int:id_chofer>/', PerfilChofer, name = 'perfil'),
	path('listar/',ListarChofer, name = 'listar'),
	path('trabajar/<int:id_chofer>/', Trabajar, name = 'trabajar'),
	path('gestion/',Gestion, name = 'gestion'),
	path('eliminar/<int:id_chofer>', EliminarChofer, name = 'eliminar'),
	path('suspender/<int:id_chofer>', SuspenderChofer, name = 'suspender'),
	path('habilitar/<int:id_chofer>', HabilitarChofer, name = 'habilitar'),
]

apps/servicio/urls.py
from django.urls import path
from apps.servicio.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = "index"),
	path('pedir', pedir, name = "pedir"),
	path('confirmar', confirmar, name = "confirmar"),
	path('pedido', RegistrarViaje, name = 'pedido'),
	path('gestion/', GestionViajes, name = 'gestion'),
	path('detalles/<int:id_viaje>', DetallesViaje, name = 'detalles'),
	path('cancelar/<int:id_viaje>', CancelarViaje, name = 'cancelar'),
	path('despachar/<int:id_viaje>', DespacharViaje, name = 'despachar'),
]

mayaca/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('home/', include('apps.home.urls', namespace = 'home')),
    path('cliente/', include('apps.cliente.urls',namespace = 'cliente')),
    path('administracion/', include('apps.administracion.urls', namespace = 'administracion')),
    path('chofer/', include('apps.chofer.urls', namespace = 'chofer')),
    path('servicio/', include('apps.servicio.urls', namespace = 'servicio')),
    path('accounts/', include ('django.contrib.auth.urls')),
]

apps/servicio/models.py
from django.db import models
from apps.cliente.models import Cliente 
from apps.chofer.models import Chofer 
from datetime import datetime 
from django.contrib.auth.models import User


# Create your models here.

class Distancia(models.Model):
	origen = models.CharField(max_length = 150)
	destino = models.CharField(max_length = 150)
	distancia = models.FloatField()


class BitacoraViaje(models.Model):
	descripcion = models.CharField(max_length = 30)
	fecha = models.DateField(datetime.today)
	usuario = models.ForeignKey(User, on_delete = models.CASCADE)

class Viaje(models.Model):
	cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
	chofer = models.ForeignKey(Chofer, on_delete = models.CASCADE)
	fecha_so = models.DateTimeField(auto_now_add=True, blank=True)
	fecha_re = models.DateTimeField()
	origen_destino = models.ForeignKey(Distancia, on_delete = models.CASCADE)
	precio = models.FloatField()
	estado = models.CharField(max_length = 1)

apps/servicio/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from apps.servicio.models import Viaje, Distancia
from apps.cliente.models import Cliente
from apps.chofer.models import Chofer
from datetime import date, datetime


# Create your views here.


def index(request):
	return render(request, 'servicio/index.html')

def pedir(request):
	return render(request, 'servicio/pedir.html')

def confirmar(request):
	if request.method == 'POST':
		origen = request.POST['origen']
		destino = request.POST['destino']
		distancia = request.POST['distancia']
		precio = float(distancia) * 5000
		clientes = Cliente.objects.all()
		contexto = {'origen':origen,
					'destino':destino,
					'distancia':distancia,
					'precio': precio,
					'clientes': clientes
					}
		return render(request, 'servicio/confirmar.html', contexto)	
	return HttpResponseRedirect(reverse('home:index'))

def RegistrarViaje(request):
	if request.method == 'POST':
		chofer = Chofer.objects.filter(trabajando = True)
		if chofer.exists() == True:
			chofer = Chofer.objects.get(trabajando = True)
		else:
			chofer = False
			return render(request, 'servicio/pedido.html', {'chofer': chofer})
		cliente = Cliente.objects.get(cedula = request.POST['cliente'])
		cuando = request.POST['fecha']
		fecha = datetime.today()
		precio = 5000

		distancia = Distancia(
			origen = request.POST['origen'],
			destino = request.POST['destino'],
			distancia = request.POST['distancia']
			)
		distancia.save()
		viaje = Viaje(
			cliente = cliente,
			chofer = chofer,
			fecha_so = fecha,
			fecha_re = fecha,
			origen_destino = distancia,
			precio = precio * float(request.POST['distancia']),
			estado = 'P'
			)
		viaje.save()
		return render(request, 'servicio/pedido.html', {'viaje': viaje, 'distancia': distancia})
	return HttpResponseRedirect(reverse('home:index'))

def DetallesViaje(request,id_viaje):
	viaje = Viaje.objects.filter(id = id_viaje)
	if viaje.exists() == True:
		viaje = Viaje.objects.get(id = id_viaje)
		return render(request, 'servicio/viaje.html', {'viaje':viaje})
	return render(request, 'servicio/viaje.html')

def GestionViajes(request):
	viajes = Viaje.objects.all()
	viajes_p = Viaje.objects.filter(estado = 'P')
	viajes_c = Viaje.objects.filter( estado = 'C')
	viajes_r = Viaje.objects.filter( estado = 'R')
	contexto = {
	'viajes': viajes,
	'viajes_p': viajes_p,
	'viajes_c': viajes_c,
	'viajes_r': viajes_r,
	}
	return render(request, 'servicio/viajes.html', contexto)

def CancelarViaje(request,id_viaje):
	viaje = Viaje.objects.get(id = id_viaje)
	viaje.estado = 'C'
	viaje.save()
	return HttpResponseRedirect(reverse('servicio:gestion'))

def DespacharViaje(request,id_viaje):
	viaje = Viaje.objects.get(id = id_viaje)
	viaje.estado = 'R'
	viaje.save()
	return HttpResponseRedirect(reverse('servicio:gestion'))

templates/servicio/confirmar.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 wrap">
			<h2 class="text-center text-primary">Para confirmar el viaje complete el formulario: </h2>
			{% if origen %}
				<form action="{% url 'servicio:pedido' %}" class="form-group" method="post">
					{% csrf_token %}
					<div class="form-group">
						<p>Origen: <strong>{{ origen }}</strong></p>
						<input type="hidden" value="{{ origen }}" name="origen">
						<p>Destino: <strong>{{ destino }}</strong></p>
						<input type="hidden" value="{{ destino }}" name="destino">
						{% if user.cliente %}
							<p>Cliente: <strong>Jonnathan</strong></p>
							<input type="hidden" value="{{ user.cliente.cedula }}" name="cliente">
						{% else %}
						<h4 class="text-center">Elija un cliente</h4>
						    {% if clientes %}
						    		<select name="cliente" id="cliente" class="form-control" style="margin-left: auto; margin-right: auto; width: 50%;">
						    			{% for cliente in clientes %}
						    				<option value="{{ cliente.cedula }}">{{ cliente.usuario.first_name }} {{ cliente.usuario.last_name }} - V-{{ cliente.cedula }}</option>
						    			{% endfor %}
						    		</select>				    						
						    {% endif %}						
						{% endif %}
						<p>Distancia: <strong>{{ distancia }} Km</strong></p>
						<input type="hidden" value="{{ distancia }}" name="distancia">
						<p>Precio: Bs.F {{ precio }}</p>
						<input type="hidden" value="25000" name="precio">
					</div>
					<div class="form-group radio">
					
						<h3 class="text-center">Indique la fecha:</h3>
						<div class="alert alert-dismissible alert-info">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<p class="text-center">
								Si elijes reservar el precio puede estar sujeto a cambios de acuerdo a la tasa actual del dia que se le preste el servicio, para mas informacion lea nuestro 
								<a href="#">Terminos y condiciones del servicio</a>
							</p>
						</div>

						<label for="ahora" class="custom-control-label">Ahora</label>
						<input type="radio" value="ahora" name="fecha" id="ahora" required>

						<label for="reservar" class="custom-control-label">Reservar</label>
						<input type="radio" value="reservar" name="fecha" id="reservar" required>

					

					</div>
						<div class="form-group" style="margin: 10px auto">
							<input type="date" class="form-control " min="2018-05-02" id="fecha_re" name="fecha_re" readonly="readonly" style="margin: 10px; margin-right: auto; margin-left: auto; width: 50%" >
							<span class="text-center">
								<button type="submit" class="btn btn-primary">Confirmar y pedir</button>
								<a href="{% url 'servicio:pedir' %}" class="btn btn-default">Cancelar</a>
							</span>
						</div>
				</form>
			{% endif %}
			
		</div>
	</div>
</div>

{% endblock %}

templates/servicio/index.html
{% extends 'base.html' %}
{% block servicios %}active{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
			  <h1 class="display-3">¡Pide un Taxi!</h1>
			  <p class="lead">
			  	Para pedir un taxi necesitas estar registrado en el sistema e ingresar... Haaz clic 
			  	<a href="{% url 'login' %}"> aquí para entrar</a>
			  </p>
			  <hr class="my-4">
			  <p>
			  	Si no estas registrado y quieres formar parte de nosotros, Haz clic 
			  	<a href="{% url 'administracion:registrar' %}"> aquí</a>
			  </p>
			  <p class="lead">
			    <a class="btn btn-primary btn-lg" href="{% url 'home:index' %}" role="button">Volver</a>
			  </p>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/servicio/pedido.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="container">
    	<div class="row">
    		<div class="col-md-12">
            {% if viaje and distancia %}
                    
                
                <h2 class="text-center">¡Taxi pedido!</h2>
                <!-- <img width="300px" src="{% static 'img/check.png' %}" alt=""> -->
                <h1 class="text-center text-success"><i class="fa fa-check" aria-hidden="true"></i></h1>
                <p class="text-center"><strong>Número de solicitud:</strong> #{{ viaje.id }}</p>
                <p><strong>Origen:</strong> {{ distancia.origen }}</p>
                <p><strong>Destino: </strong>{{ distancia.destino }}</p>
                <p class="text-center"><strong>Precio</strong>: Bs. {{ viaje.precio }} </p>
                <p class="text-center"><strong>Nombre del Chofer:</strong> {{ viaje.chofer.usuario.first_name }} {{ viaje.chofer.usuario.last_name }}</p>
               <div class="botones" style="display: flex; justify-content: end;">
                    <a href="{% url 'servicio:detalles' viaje.id %}" class="btn btn-primary" style="left: 0">Ver detalles</a>
                   <a href="{% url 'home:index' %}" class="btn btn-success" style="left: 0">Pagina de inicio</a>
               </div>
            {% else %}
                <h1 class="text-primary text-center">
                    Lo sentimos no hay chofer disponible intentelo mas tarde :(
                </h1>       
                <h1 class="text-center text-primary" style="font-size: 110px"><i class="fa fa-chain-broken" aria-hidden="true"></i></h1>
            {% endif %}
            </div>
    	</div>
    </div>
{% endblock content %}

templates/servicio/pedir.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header %}
{% endblock %}
{% block content %}
<script type='text/javascript' src='https://maps.googleapis.com/maps/api/js?key=AIzaSyBzq5jw8k2nNtCAg6jItQ5B_8z6Zi7IuSA'></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/servicio/estilos.css' %}">
<script src="{% static 'js/servicio/mapa.js' %}"></script>
	<div id="map-canvas"></div>


<div class="ventana" style="width: 100%; height: 100%; top: 1px; background: rgba(0,0,0, .3); position: absolute; z-index: 2200; cursor: pointer;" id="ventana" onclick="ocultar()">
	<img src="{% static 'img/tutorial.jpg' %}" alt="" width="100%"; height="100%;">
</div>

	<div id="logo" class="buscador" style="z-index: 2001; left: 0; top: 0; width: 185px; height: 60px; background: #2C3E50; opacity: 0.8;">
		<a class="navbar-brand" href="{% url 'home:index' %}">
		  	<img src="{% static 'img/icono.ico' %}" alt="">
		  	MayacaExpress
		  </a>
	</div>

	<div class="buscador card border-success mb-3 formulario" style="max-width: 280px;" class="form-control">
		<form action="{% url 'servicio:confirmar' %}" method="POST" id="formulario">
			{% csrf_token %}
				<div class="form-group">
				  <input type="text" class="form-control" placeholder="Origen" id="origen" name="origen">
				  <input type="hidden" name="origen" id="origen">
				</div>
				<div class="form-group">
				  <input type="text" class="form-control" placeholder="Destino" id="destino" name="destino">
				  <input type="hidden" name="destino" id="destino">
					<input type="hidden" name="distancia" id="distancia" class="form-control distancia-form" style="display: none">
				</div>
			<button type="button" class="btn btn-primary" id="calcular">Calcular</button>
			<button type="submit" class="btn btn-success" style="margin-top: 2px; display: none;" id="btn-confirmar">Confirmar</button>
		</form>
		<div id="directionsPanel">
			<p>
				Distancia total: <strong><span id="total"></span></strong>
				<img src="{% static 'img/loading.gif' %}" alt="" width="25px" id="cargando" style="display: none">
			</p>
		</div>
	</div>
<script>
	var bandera = false

	 $("#formulario").submit(function() {
      if (bandera == false) {
        return false;
      } else 
          return true;      
    });

 $(window).resize(function(){
  
  var anchoVentana = $(window).width();
      var anchoFormulario = $('.formulario').width();

      $('.formulario').css({
        'left': ((anchoVentana - anchoFormulario )/2) - 12
    });
});

 var anchoVentana = $(window).width();
      var anchoFormulario = $('.formulario').width();

      $('.formulario').css({
        'left': ((anchoVentana - anchoFormulario )/2) - 12
    });
 function ocultar() {
 	document.getElementById('ventana').style.display = 'none';
 }
</script>
{% endblock %}

{% block footer %}
{% endblock %}

templates/servicio/viaje.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				{% if viaje %}
				<h2 class="text-primary text-center">Detalles del viaje <i class="fa fa-taxi" aria-hidden="true"></i></h2>
				<p><strong>Número de Viaje:</strong> #{{ viaje.id }}</p>
				<p><strong>Cliente:</strong> {{ viaje.cliente.usuario.first_name }}</p>
				<p><strong>Chofer:</strong> {{ viaje.chofer.usuario.first_name }}</p>
				<p><strong>Fecha de Solicitud:</strong> {{ viaje.fecha_so }}</p>
				<p><strong>Fecha de Carrera:</strong> {{ viaje.fecha_re }}</p>
				<p><strong>Precio: </strong>{{ viaje.precio|floatformat:2 }} Bs.</p>
				<p><strong>Estado: </strong> 
					{% if viaje.estado == 'P' %}
					    Pendiente
					{% elif viaje.estado == 'C' %}
						Cancelado
					{% else %}
					    Realizado			
					{% endif %}
				</p>
				<p><strong>Origen: </strong> {{ viaje.origen_destino.origen }}</p>
				<p><strong>Destino: </strong> {{ viaje.origen_destino.destino }}</p>
				<p><strong>Distancia: </strong> {{ viaje.origen_destino.distancia|floatformat:3 }} Km</p>
				{% else %}
				    <h1 class="text-center text-primary">El viaje al que intenta acceder no esta disponible</h1>
				{% endif %}
				<a href="#" class="btn btn-primary">Modificar</a>
				<a href="{% url 'servicio:gestion' %}" class="btn btn-info">Volver</a>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
{% endblock content %}

templates/servicio/viajes.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="text-center text-muted"> Administracion de Viajes</h2>
			</div>
		</div>
	</div>


    <div class="container">
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-tabs">
			  <li class="nav-item">
			    <a class="nav-link  active show" data-toggle="tab" href="#viaje_p">Viajes Pendientes</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="tab" href="#viaje_r">Viajes Realizados</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="tab" href="#viaje_c">Viajes Cancelados</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="tab" href="#viajes">Todos los Viajes</a>
			  </li>
			  <!-- <li class="nav-item">
			    <a class="nav-link disabled" href="#">Disabled</a>
			  </li> -->
			</ul>
			<div id="myTabContent" class="tab-content">
			  <div class="tab-pane fade  active show" id="viaje_p">
			  	<a href="{% url 'servicio:pedir' %}" style="margin: 4px 10px" class="btn btn-success"><i class="fa fa-plus-circle" aria-hidden="true"></i> Agregar un nuevo viaje</a>
				  	{% if  viajes_p %}
			    <table class="table table-hover">
				  <thead>
				    <tr>
				      <th scope="col">ID</th>
				      <th scope="col">Chofer</th>
				      <th scope="col">Cliente</th>
				      <th scope="col">Precio</th>
				      <th scope="col">Fecha de Solicitud</th>
				      <th scope="col" class="text-center">Acciones</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for viaje in viajes_p %}
				  	<tr class="table-default">
				      <th scope="row">{{ viaje.id }}</th>
				      <td>{{ viaje.chofer.usuario.first_name }}</td>
				      <td>{{ viaje.cliente.usuario.first_name }}</td>
				      <td>{{ viaje.precio }}</td>
				      <td>{{ viaje.fecha_so }}</td>
				      <td>
				      	<a href="{% url 'servicio:detalles' viaje.id %}" class="btn btn-primary" title="Ver Viaje"><i class="fa fa-info" aria-hidden="true"></i></a>
				      	<a href="#confirm2" data-toggle="modal" class="btn btn-danger" title="Cancelar Viaje"><i class="fa fa-times" aria-hidden="true" title="Cancelar Viaje"></i></a>
						<!-- =========== Modal de Cancelar ============  -->
						<div class="modal fade" id="confirm2">
						  <div class="modal-dialog" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h4 class="modal-title">Confirmacion</h4>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        <p>¿Esta seguro que desea Cancelar el viaje #{{ viaje.id }}?</p>
						      </div>
						      <div class="modal-footer">
						        <a href="{% url 'servicio:cancelar' viaje.id %}" class="btn btn-danger">Cancelar</a>
						        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
						      </div>
						    </div>
						  </div>
						</div>
						<!-- =========== Fin de modal de Cancelar ============ -->
						<a href="#confirm1" data-toggle="modal" class="btn btn-success" title="Despachar Viaje"><i class="fa fa-check" aria-hidden="true"></i></a>
						<!-- =========== Modal de Despacho ============  -->
						<div class="modal fade" id="confirm1">
						  <div class="modal-dialog" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h4 class="modal-title">Confirmacion</h4>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        <p>¿Esta seguro que desea despachar el viaje #{{ viaje.id }}?</p>
						      </div>
						      <div class="modal-footer">
						        <a href="{% url 'servicio:despachar' viaje.id %}" class="btn btn-success">Despachar</a>
						        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
						      </div>
						    </div>
						  </div>
						</div>
						<!-- =========== Fin de modal de despacho ============ -->
						<a href="#" class="btn btn-warning" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
				      </td>
				    </tr>
				    {% endfor %}
				    {% else %}
				    <h3 class="text-center text-primary">No hay viajes disponibles</h3>
				  	{% endif %}
				  </tbody>
				</table> 
			  </div>
			  <div class="tab-pane fade" id="viaje_r">
			    <table class="table table-hover">
				  <thead>
				    <tr>
				      <th scope="col">ID</th>
				      <th scope="col">Chofer</th>
				      <th scope="col">Cliente</th>
				      <th scope="col">Precio</th>
				      <th scope="col">Fecha de Solicitud</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% if  viajes_r %}
				  	{% for viaje in viajes_r %}
				  	<tr class="table-warning">
				      <th scope="row">{{ viaje.id }}</th>
				      <td>{{ viaje.chofer.usuario.first_name }}</td>
				      <td>{{ viaje.cliente.usuario.first_name }}</td>
				      <td>{{ viaje.precio }}</td>
				      <td>{{ viaje.fecha_so }}</td>
				    </tr>
				    {% endfor %}
				  	{% endif %}
				  </tbody>
				</table> 
			  </div>
			  <div class="tab-pane fade" id="viaje_c">
			    <table class="table table-hover">
				  <thead>
				    <tr>
				      <th scope="col">ID</th>
				      <th scope="col">Chofer</th>
				      <th scope="col">Cliente</th>
				      <th scope="col">Precio</th>
				      <th scope="col">Fecha de Solicitud</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% if  viajes_c %}
				  	{% for viaje in viajes_c %}
				  	<tr class="table-danger">
				      <th scope="row">{{ viaje.id }}</th>
				      <td>{{ viaje.chofer.usuario.first_name }}</td>
				      <td>{{ viaje.cliente.usuario.first_name }}</td>
				      <td>{{ viaje.precio }}</td>
				      <td>{{ viaje.fecha_so }}</td>
				    </tr>
				    {% endfor %}
				  	{% endif %}
				  </tbody>
				</table> 
			  </div>
			  <div class="tab-pane fade" id="viajes">
				<table class="table table-hover">
				  <thead>
				    <tr>
				      <th scope="col">ID</th>
				      <th scope="col">Chofer</th>
				      <th scope="col">Cliente</th>
				      <th scope="col">Precio</th>
				      <th scope="col">Fecha de Solicitud</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% if  viajes %}
				  	{% for viaje in viajes %}
				  	<tr class="table-success">
				      <th scope="row">{{ viaje.id }}</th>
				      <td>{{ viaje.chofer.usuario.first_name }}</td>
				      <td>{{ viaje.cliente.usuario.first_name }}</td>
				      <td>{{ viaje.precio }}</td>
				      <td>{{ viaje.fecha_so }}</td>
				    </tr>
				    {% endfor %}
				  	{% endif %}
				  </tbody>
				</table> 
			  </div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}