apps/chofer/urls.py
from django.urls import path
from apps.chofer.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = 'index'),
	path('registrar/', RegistrarChofer, name = 'registrar'),
	path('editar/<int:id_chofer>/', EditarChofer, name = 'editar'),
	path('perfil/<int:id_chofer>/', PerfilChofer, name = 'perfil'),
	path('listar/',ListarChofer, name = 'listar'),
	path('trabajar/<int:id_chofer>/', Trabajar, name = 'trabajar'),
	path('gestion/',Gestion, name = 'gestion'),
	path('eliminar/<int:id_chofer>', EliminarChofer, name = 'eliminar'),
	path('suspender/<int:id_chofer>', SuspenderChofer, name = 'suspender'),
	path('habilitar/<int:id_chofer>', HabilitarChofer, name = 'habilitar'),
]

apps/cliente/urls.py
from django.urls import path
from apps.cliente.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = 'index'),
	path('registrar/', RegistrarCliente, name = 'registrar'),
	path('perfil/<int:id_cliente>/', PerfilCliente, name = 'perfil'),
	path('editar/<int:id_cliente>/', EditarCliente, name = 'editar'),
	path('viajes/<int:id_cliente>/', ViajesCliente, name = 'viajes'),
	path('listar/', ListarClientes, name = 'listar'),
]

apps/home/urls.py
from django.conf.urls import include
from django.urls import path
from apps.home.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = "index"),
	path('acerca_de/', acerca_de, name = "acerca_de"),
	path('terminos-y-condiciones/', terminos, name = "terminos"),
]

apps/servicio/urls.py
from django.urls import path
from apps.servicio.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = "index"),
	path('pedir', pedir, name = "pedir"),
	path('confirmar', confirmar, name = "confirmar"),
	path('pedido', RegistrarViaje, name = 'pedido'),
	path('gestion/', GestionViajes, name = 'gestion'),
	path('detalles/<int:id_viaje>', DetallesViaje, name = 'detalles'),
	path('cancelar/<int:id_viaje>', CancelarViaje, name = 'cancelar'),
	path('despachar/<int:id_viaje>', DespacharViaje, name = 'despachar'),
]

mayaca/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('home/', include('apps.home.urls', namespace = 'home')),
    path('cliente/', include('apps.cliente.urls',namespace = 'cliente')),
    path('administracion/', include('apps.administracion.urls', namespace = 'administracion')),
    path('chofer/', include('apps.chofer.urls', namespace = 'chofer')),
    path('servicio/', include('apps.servicio.urls', namespace = 'servicio')),
    path('accounts/', include ('django.contrib.auth.urls')),
]

templates/base.html
  {% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<meta charset="UTF-8">
	<title>MayacaExpress</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
	<link rel="stylesheet" href="{% static 'css/awesome/font-awesome.min.css' %}">
	<meta name="theme-color" content="#083756" />
	<link rel="icon" type="image/png" href="{% static 'img/icono.ico' %}" />
	<style>
		body {font-family: 'Roboto', sans-serif;}
	</style>
</head>
<body>
	{% block header %}
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="margin-bottom: 20px">
		  <a class="navbar-brand" href="{% url 'home:index' %}">
		  	<img src="{% static 'img/icono.ico' %}" alt=""> MayacaExpress</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarColor01">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item {% block inicio %}{% endblock %}">
		        <a class="nav-link" href="{% url 'home:index' %}">Inicio <span class="sr-only">(current)</span></a>
		      </li>
		      <li class="nav-item {% block servicios %}{% endblock %}">
		      	{% if user.is_authenticated %}
		      		<a class="nav-link" href="{% url 'servicio:pedir' %}">Servicio</a>
		        {% else %}
		        	<a class="nav-link" href="{% url 'servicio:index' %}">Servicio</a>
		        {% endif %}
		      </li>
		      <li class="nav-item {% block acerca_de %}{% endblock %}">
		        <a class="nav-link" href="{% url 'home:acerca_de' %}">Acerca de</a>
		      </li>
		      {% if not user.is_authenticated %}
		      <li class="nav-item {% block chofer %}{% endblock %}">
		        <a class="nav-link" href="{% url 'chofer:index' %}">Unete a nuestra empresa</a>
		      </li>
		      {% else %}
		      	{% if user.chofer %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'chofer:perfil' user.chofer.id %}">
							Trabajando: 
							{% if user.chofer.trabajando == True %}
							    Si <i class="fa fa-check-circle-o" aria-hidden="true" style="color: #79e342"></i>
							{% else %}
								No <i class="fa fa-times-circle" aria-hidden="true" style="color: #f02719"></i>
							{% endif %}
						</a>
					</li>
		      	{% endif %}
		      {% endif %}
		    </ul>
		{% if user.is_authenticated %}
		    <ul class="nav nav-pills">
			  <li class="nav-item dropdown show">
			  	<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">
					{% if user.chofer %}
			  		<i class="fa fa-taxi" aria-hidden="true"></i>   
					{% elif user.cliente %}
			  		<i class="fa fa-user-o" aria-hidden="true"></i> 
			  		{% elif user.empleado.rol == 'Empleado' %}
			  		<i class="fa fa-id-card" aria-hidden="true"></i>
			  		{% elif user.empleado or user %}
			  		<i class="fa fa-steam" aria-hidden="true"></i>
					{% endif %}
			    	    {% if user.first_name == '' %}
							(NombreNoEstablecido)	
			    	    {% else %}		    	    
							{{ user.first_name }}
			    	    {% endif %}
			    </a>
			    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
			    	 <!-- ================== Modificar Perfil ===============  -->
			      {% if user.cliente %}
			      <a class="dropdown-item" href="{% url 'cliente:editar' user.cliente.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Modificar perfil  </a>
			      {% elif user.chofer %}
			      <a class="dropdown-item" href="{% url 'chofer:editar' user.chofer.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Modificar perfil  </a>
			      {% elif user.empleado %}
			      <a class="dropdown-item" href="{% url 'administracion:editar' user.empleado.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Modificar perfil  </a>
			      {% endif %}
			      <!-- ================== Administrar ====================  -->
				  {% if user.empleado %}
			      <a class="dropdown-item" href="{% url 'administracion:panel' %}"> <i class="fa fa-binoculars" aria-hidden="true"></i> Administrar </a>
			      {% elif user.chofer %}
			      <a class="dropdown-item" href="{% url 'chofer:gestion' %}"> <i class="fa fa-binoculars" aria-hidden="true"></i> Mis Viajes </a>
				  {% endif %}
				  <!-- =========== Viajes Cliente =============== -->
				  {% if user.cliente %}
				  <a class="dropdown-item" href="{% url 'cliente:viajes' user.cliente.id %}"><i class="fa fa-binoculars" aria-hidden="true"></i> Viajes</a>    
				  {% endif %}
				  <!-- ============ Fin Viajes Cliente ========== -->

				  <!-- ================= Cambiar Precio ================  -->
  {% if user.empleado %}
      {% if user.empleado.rol == 'Administrador' %}
		<a href="#confirm1" data-toggle="modal" class="dropdown-item" title="Despachar Viaje"><i class="fa fa-usd" aria-hidden="true"></i> Cambiar Precio</a>
      {% endif %}				  
  {% endif %}
				  <!-- ================= Fin Cambiar Precio ================  -->

				  <!-- =============== Perfil ===================== -->
				  {% if user.cliente %}
			      <a class="dropdown-item" href="{% url 'cliente:perfil' user.cliente.id %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Perfil </a>
				  {% elif user.chofer %}
				  <a class="dropdown-item" href="{% url 'chofer:perfil' user.chofer.id %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Perfil </a>
				  {% elif user.empleado or user %}
			      <a class="dropdown-item" href="{% url 'administracion:perfil' user.empleado.id %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Perfil </a>
				  {% endif %}
				  <!-- ====================== Log Out ====================== -->
			      <div class="dropdown-divider"></div>
			      <a class="dropdown-item" href="{% url 'logout' %}"> <i class="fa fa-sign-out" aria-hidden="true"></i> Salir</a>
			    </div>
			  </li>
			  <li class="nav-item">
		        <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Salir 
</a>
			 </li>
			</ul>
    	{% else %}
    			<ul class="nav nav-pills">
    				 <li class="nav-item">
				        <a class="nav-link" href="{% url 'login' %}">Ingresar <i class="fa fa-sign-in" aria-hidden="true"></i>
</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="{% url 'cliente:registrar' %}">Registrarse</a>
				      </li>
    			</ul>	    	
    	{% endif %}
		  </div>
		</nav>
{% if user.is_authenticated %}
	{% if user.empleado %}
		{% if user.empleado.rol == 'Administrador' %}
		<div class="modal fade" id="confirm1">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h4 class="modal-title">Cambiar de Precio <i class="fa fa-usd" aria-hidden="true"></i></h4>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<!-- ====== Formulario ======= -->
							<div class="form-group" style="margin: 0 70px;">
							  <label class="control-label">Nuevo Precio del Servicio (Por Kilometro)</label>
							  <div class="form-group">
							    <div class="input-group mb-3">
							      <div class="input-group-prepend">
							        <span class="input-group-text">Bs.</span>
							      </div>
							      <input class="form-control" aria-label="Amount (to the nearest dollar)" type="text">
							      <div class="input-group-append">
							        <span class="input-group-text">.00</span>
							      </div>
							    </div>
							  </div>
							</div>
							<!-- ====== Fin Formulario ======= -->
							<p class="text-primary">
								Esta tarea solo puede ser realizada por un administrador, de ahora en adelante el precio por el servicio (valor por kilometros) sera el que establezca
							</p>
							<h3 class="text-center text-primary">
								<i class="fa fa-steam" aria-hidden="true"></i> {{ user.first_name }} {{ user.last_name }}
							</h3>
						</div>
						<div class="modal-footer">
							<a href="#" class="btn btn-success">Despachar</a>
							<button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
						</div>
					</div>
				</div>
			</div>
		{% endif %}
	{% endif %}
{% endif %}
	{% endblock %}
	{% block content %}
	{% endblock %}
	{% block footer %}
		<footer class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="sociales text-center">
							<a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
							<a href="#" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
							<a href="#" class="twitter"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
							<a href="#" class="pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="parrafo">
							<p class="text-center">
								Reservado todos los derechos Copyright 2018 Reservado Todos los derechos
							</p>
						</div>			
					</div>
				</div>
			</div>
		</footer>
		{% block transformacion %}
		    <script>
				var campos = document.getElementsByTagName('input');

				for (var campo of campos){

					if (campo.type != undefined && (campo.type === "password" || campo.type === "text")){
						campo.setAttribute('class', 'form-control');
						campo.setAttribute('required', '');
					}
				}

			</script>
		{% endblock transformacion %}
	{% endblock %}
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="{% static 'js/servicio/confirmar.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>