apps/administracion/urls.py
from django.urls import path
from apps.administracion.views import *
from django.contrib.auth.decorators import login_required

app_name = 'apps'

urlpatterns = [
	path('', index, name = 'administracion'),
	path('registrar/', RegistrarEmpleado, name = 'registrar'),
	path('listar/', ListarEmpleado, name = 'listar' ),
	path('eliminar/<int:pk>/',UsuarioDelete.as_view(), name = 'eliminar'),
	path('editar/<int:id_empleado>/',EditarEmpleado, name = 'editar'),
	path('suspender/<int:id_usuario>',Suspender, name = 'suspender'),
	path('habilitar/<int:id_usuario>',Habilitar, name = 'habilitar'),
	path('perfil/<int:id_empleado>',PerfilEmpleado, name = 'perfil'),
	path('panel/',Panel, name = 'panel'),
	path('reportes/', Reportes, name = 'reportes'),
	path('permisos/<int:id_empleado>',permisos, name = 'permisos'),
]

apps/chofer/urls.py
from django.urls import path
from apps.chofer.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = 'index'),
	path('registrar/', RegistrarChofer, name = 'registrar'),
	path('editar/<int:id_chofer>/', EditarChofer, name = 'editar'),
	path('perfil/<int:id_chofer>/', PerfilChofer, name = 'perfil'),
	path('listar/',ListarChofer, name = 'listar'),
	path('trabajar/<int:id_chofer>/', Trabajar, name = 'trabajar'),
	path('gestion/',Gestion, name = 'gestion'),
	path('eliminar/<int:id_chofer>', EliminarChofer, name = 'eliminar'),
	path('suspender/<int:id_chofer>', SuspenderChofer, name = 'suspender'),
	path('habilitar/<int:id_chofer>', HabilitarChofer, name = 'habilitar'),
]

apps/home/urls.py
from django.conf.urls import include
from django.urls import path
from apps.home.views import *

app_name = 'apps'

urlpatterns = [
	path('', index, name = "index"),
	path('acerca_de/', acerca_de, name = "acerca_de"),
	path('terminos-y-condiciones/', terminos, name = "terminos"),
]

mayaca/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('home/', include('apps.home.urls', namespace = 'home')),
    path('cliente/', include('apps.cliente.urls',namespace = 'cliente')),
    path('administracion/', include('apps.administracion.urls', namespace = 'administracion')),
    path('chofer/', include('apps.chofer.urls', namespace = 'chofer')),
    path('servicio/', include('apps.servicio.urls', namespace = 'servicio')),
    path('accounts/', include ('django.contrib.auth.urls')),
]

apps/administracion/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, datetime

# Create your models here.


class Permisos(models.Model):
	agregar = models.BooleanField()
	eliminar = models.BooleanField()
	editar = models.BooleanField()
	suspender = models.BooleanField()
	habilitar = models.BooleanField()


class Empleado(models.Model):
	usuario = models.OneToOneField(User, on_delete=models.CASCADE)
	foto = models.ImageField(upload_to='EmpleadoFotos/', blank=True)
	cedula = models.CharField(max_length = 10, blank = True, unique= True)
	sueldo = models.FloatField(blank = True)
	fecha_nacimiento = models.DateField(null=True, blank=True, default=None)
	direccion = models.CharField(max_length = 80, blank = True)
	telefono = models.CharField(max_length = 14, blank = True)
	rol = models.CharField(max_length = 20, blank = True)
	permisos = models.OneToOneField(Permisos, on_delete=models.CASCADE)

	def __str__(self):
		return self.usuario.username + ' ' + self.usuario.last_name

class BitacoraEmpleado(models.Model):
	user = models.ForeignKey(User, on_delete = 'cascade', default = None)
	descripcion = models.CharField(max_length = 12)
	fecha = models.DateField(default=datetime.today)

apps/administracion/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from apps.administracion.models import *

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
 

class FormUser(UserCreationForm):
	class Meta:
		model = User
		fields = [
			'username',
			'first_name',
			'last_name',
			'email',
			]
		labels = {
			'username' : 'Nombre de Usuario',
			'first_name': 'Nombre',
			'last_name': 'Apellido' ,
			'email': 'Correo Electronico',
		}
		widgets = {
			'username' : forms.TextInput(attrs={'class':'form-control'}),
			'first_name': forms.TextInput(attrs={'class':'form-control'}),
			'last_name': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control'}),
		}

class FormEmpleado(forms.ModelForm):
	class Meta:
		model = Empleado 
		fields = (
			'cedula',
			'sueldo',
			'fecha_nacimiento',
			'direccion',
			'telefono',
			'foto'
			)
		labels = {
			'cedula': 'Cedula',
			'sueldo': 'Sueldo',
			'fecha_nacimiento': 'Fecha Nacimiento',
			'direccion': 'Direccion',
			'telefono': 'Telefono',
			'foto': 'Foto del Empleado',
		}
		widgets = {
			'cedula': forms.TextInput(attrs={'class':'form-control', 'required': ''}),
			'sueldo': forms.TextInput(attrs={'class':'form-control', 'required': ''}),
			'fecha_nacimiento': forms.TextInput(attrs={'class':'form-control', 'required': ''}),
			'direccion': forms.TextInput(attrs={'class':'form-control', 'required': ''}),
			'telefono': forms.TextInput(attrs={'class':'form-control', 'required': ''}),
		}

class FormPermisos(forms.ModelForm):
	class Meta:
		model = Permisos
		fields = (
			'agregar',
			'eliminar',
			'editar',
			'suspender',
			'habilitar'
			)
		labels = {
			'agregar': 'Agregar',
			'eliminar': 'Eliminar',
			'editar': 'Editar',
			'suspender': 'Suspender',
			'habilitar': 'Habilitar',
		}

apps/administracion/views.py
from django.shortcuts import render
from apps.administracion.forms import FormUser, FormEmpleado, FormPermisos
from apps.administracion.models import *
from django.views.generic import CreateView,ListView,DeleteView,UpdateView
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy,reverse
from apps.servicio.models import *
from apps.chofer.models import *
from mayaca.settings import Precio



# Create your views here.

def index(request):
	return render(request, 'administracion/index.html')

class UsuarioDelete(DeleteView):
	model = User 
	template_name = 'administracion/delete.html'
	success_url = reverse_lazy('administracion:listar')


def Suspender(request, id_usuario):
	usuario = User.objects.get(id = id_usuario)
	usuario.is_active = 0
	if request.method == 'POST':
		usuario.save()
		return HttpResponseRedirect(reverse('administracion:listar'))
	return render(request,'administracion/suspender.html', {'usuario':usuario})

def Habilitar(request, id_usuario):
	usuario = User.objects.get(id = id_usuario)
	usuario.is_active = 1
	if request.method == 'POST':
		usuario.save()
		return HttpResponseRedirect(reverse('administracion:listar'))
	return render(request,'administracion/habilitar.html', {'usuario':usuario})



def RegistrarEmpleado(request):
	bandera = False
	if request.user.is_authenticated:
		usuario_actual = request.user.id
		empleado = Empleado.objects.filter(usuario_id = usuario_actual)
		if empleado.exists() == True:
			bandera = True

	if bandera == True:
		if request.method == 'POST':
			user_form = FormUser(request.POST)
			empleado_form = FormEmpleado(request.POST, request.FILES)
			permisos_form = FormPermisos(request.POST)
			if empleado_form.is_valid() and user_form.is_valid() and permisos_form.is_valid():
				user = user_form.save()
				user.refresh_from_db()
				permisos = permisos_form.save()

				if permisos.agregar == False or permisos.eliminar == False or permisos.editar == False or permisos.suspender == False or permisos.habilitar == False:
					rol = 'Empleado'
				else:
					rol = 'Administrador'

				empleado = Empleado(
					usuario = user, 
					foto = request.FILES['foto'],
					cedula = empleado_form.cleaned_data['cedula'],
					sueldo = empleado_form.cleaned_data['sueldo'],
					fecha_nacimiento = empleado_form.cleaned_data['fecha_nacimiento'],
					direccion = empleado_form.cleaned_data['direccion'],
					telefono = empleado_form.cleaned_data['telefono'],
					rol = rol,
					permisos = permisos
					)
				empleado.save()
				bitacora = BitacoraEmpleado(
					user = request.user,
					descripcion = "Registro"
					)
				bitacora.save()
				if request.user.is_authenticated:
					return HttpResponseRedirect(reverse('administracion:listar'))
				login(request, user)
				return HttpResponseRedirect(reverse('home:index'))
		else:
			user_form = FormUser
			empleado_form = FormEmpleado
			permisos_form = FormPermisos
		return render(request, 'administracion/registro.html',{
	       	'user_form': user_form,
	       	'empleado_form': empleado_form,
	       	'permisos_form': permisos_form
	       	})
	return render(request, 'administracion/registro.html')

def EditarEmpleado(request,id_empleado):
	bandera = False
	if request.user.is_authenticated:
		usuario_actual = request.user.id
		empleado = Empleado.objects.filter(usuario_id = usuario_actual)
		if empleado.exists() == True:
			bandera = True
	bandera2 = False
	empleado = Empleado.objects.filter(id = id_empleado)
	if empleado.exists() == True:
		bandera2 = True

	if bandera == True and bandera2 == True:
		usuario_actual = request.user
		editar = True
		empleado = Empleado.objects.get(id = id_empleado)
		if request.method == 'GET':
			empleado_form = FormEmpleado(instance = empleado)
			user_form = FormUser(instance = empleado.usuario)
			permisos_form = FormPermisos(instance = empleado.permisos)
		else:
			empleado_form = FormEmpleado(request.POST, instance = empleado)
			user_form = FormUser(request.POST, instance = empleado.usuario)
			permisos_form = FormPermisos(request.POST, instance = empleado.permisos)
			if empleado_form.is_valid() and user_form.is_valid() and permisos_form.is_valid():
				usuario = user_form.save()
				empleado_form.save()
				permisos_form.save()
				bitacora = BitacoraEmpleado(
					user = request.user,
					descripcion = "Edicion"
					)
				bitacora.save()
				if request.user.is_authenticated:
					login(request, usuario)
					return HttpResponseRedirect(reverse('administracion:listar'))
				print('ola k ase 2')
				return HttpResponseRedirect(reverse('home:index'))
		return render(request, 'administracion/registro.html',{
			'empleado_form': empleado_form,
			'user_form': user_form,
			'permisos_form': permisos_form,
			'editar': editar
			})
	return render(request, 'administracion/registro.html')


def ListarEmpleado(request):
	if request.user.is_authenticated:
		usuario_actual = request.user.id 
		empleado = Empleado.objects.filter(usuario = usuario_actual)
		if empleado.exists() == True: 
			empleados = Empleado.objects.all()
			contexto = {'empleados': empleados}
			return render(request, 'administracion/lista.html', contexto)
	return render(request, 'administracion/lista.html')

def PerfilEmpleado(request, id_empleado):
	if request.user.is_authenticated:
		usuario_actual = request.user.id 
		empleado = Empleado.objects.filter(usuario = usuario_actual)
		if empleado.exists() == True:
			empleado = Empleado.objects.filter(id = id_empleado)
			if empleado.exists() == True:
				empleado = Empleado.objects.get(id = id_empleado)
				return render(request, 'administracion/perfil.html', {'empleado':empleado})
	return render(request, 'administracion/perfil.html')

def Panel(request):
	if request.user.is_authenticated:
		usuario_actual = request.user.id 
		empleado = Empleado.objects.filter(usuario = usuario_actual)
		if empleado.exists() == True:
			panel = True
			bandera_chofer = False
			choferes = Chofer.objects.all()
			for chofer in choferes:
				if chofer.usuario.is_active == False:
					bandera_chofer = True
			return render(request, 'administracion/panel.html',{'bandera_chofer':bandera_chofer, 'panel':panel})	
	return render(request, 'administracion/panel.html')

def CambiarPrecio(request,precio_nuevo):
	Precio = precio_nuevo
	return HttpResponseRedirect(reverse('home:index'))

def Reportes(request):
	usuario_actual = request.user.id 
	empleado = Empleado.objects.filter(usuario_id = usuario_actual)
	if empleado.exists() == True:
		viajes = Viaje.objects.all()
		contexto = {'viajes': viajes}
		return render(request, 'administracion/reportes.html', {'contexto': contexto})
	return render(request, 'administracion/reportes.html')

def permisos(request,id_empleado):
	bandera = False
	usuario_actual = request.user.id
	empleado = Empleado.objects.filter(usuario = usuario_actual)
	if empleado.exists() == True:
		empleado = Empleado.objects.filter(id = id_empleado)
		if empleado.exists() == True:
			bandera = True
			empleado = Empleado.objects.get(id = id_empleado)

	if bandera == True:
		return render(request, 'administracion/permisos.html',{'empleado':empleado})
	return render(request, 'administracion/permisos.html')

templates/administracion/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<h2>Pagina principal de administracion</h2>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit reprehenderit praesentium quis nesciunt nihil ut, quasi sit! Debitis doloribus impedit, asperiores voluptate dolorem! Sit ipsum, alias odit unde similique perferendis. <a href="{% url 'administracion:registrar' %}">Registrate</a>
	</p>
{% endblock %}

templates/administracion/lista.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}


  {% if empleados %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-primary text-center">Lista de Empleados</h2>
    </div>
    <div class="col-md-12">
      {% if user.empleado.permisos.agregar == True %}
      <a href="{% url 'administracion:registrar' %}" class="btn btn-primary">Agregar Nuevo Empleado</a>
      {% endif %}
      <a href="#" class="btn btn-info">Otra opcion Aqui</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- =================== Tabla de Empleados ======================= -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Usuario</th>
            <th scope="col">Nombre</th>
            <th scope="col">Correo Electrónico</th>
            <th scope="col">Rol</th>
            <th scope="col">Permisos</th>
            <th class="text-center">Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% if empleados %}
          	{% for empleado in empleados %}
      		    <tr>
      		      <th scope="row">{{ empleado.id }}</th>
      		      <td>{{ empleado.usuario.username }}</td>
      		      <td>{{ empleado.usuario.first_name }} {{ empleado.usuario.last_name }}</td>
      		      <td>{{ empleado.usuario.email }}</td>
      		      <td>{{ empleado.rol }}</td>
                <td><a href="{% url 'administracion:permisos' empleado.id %}" class="btn btn-primary">Ver Permisos</a></td>
      		      <td>
                  {% if empleado.usuario.id == user.id %}
                  {% else %}
                    {% if user.empleado.permisos.eliminar == True %}
                  <a href="{% url 'administracion:eliminar' empleado.usuario.id %}" class="btn btn-danger" title="Eliminar"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                    {% endif %}
                    {% if user.empleado.permisos.suspender == True %}
                  {% if empleado.usuario.is_active == 1 %}
                  <a href="{% url 'administracion:suspender' empleado.usuario.id %}" class="btn btn-warning" title="Suspender"><i class="fa fa-lock" aria-hidden="true"></i></a>
                  {% else %}
                  <a href="{% url 'administracion:habilitar' empleado.usuario.id %}" class="btn btn-success" title="Habilitar"><i class="fa fa-unlock" aria-hidden="true"></i></a>
                  {% endif %}
                    {% endif %}
                    {% if user.empleado.permisos.editar == True %}
                  <a href="{% url 'administracion:editar' empleado.id %}" class="btn btn-primary" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    {% endif %}
                  {% endif %}
                  <a href="{% url 'administracion:perfil' empleado.id %}" class="btn btn-info" title="Perfil">Perfil</i></a>
                </td>
              </tr>
            {% endfor %}
          {% else %}
          <h2>No hay Registros Disponibles</h2>
          {% endif %}
        </tbody>
      </table> 
  <!-- =================== FinTabla de Empleados ======================= -->
    </div>
  </div>
  <!-- <div class="row">
    <div class="col-md-4"></div>
      <div class="col-md-4">
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-success">Anterior</a>
        {% endif %}{% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-success">Siguiente</a>
        {% endif %}     
      </div>
    <div class="col-md-4"></div>
  </div> -->

</div>
  {% else %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center text-primary">El empleado al que intenta acceder no esta disponible o no tiene los permisos necesarios para acceder</h2>
      <h1 class="text-center text-primary" style="font-size: 110px;"><i class="fa fa-chain-broken" aria-hidden="true"></i></h1>
    </div>
    <div class="col-md-12">
      <a href="{% url 'home:index' %}" class="btn btn-lg btn-primary" style="display: block">Volver a la pagina principal</a>
    </div>
    </div>
</div>
{% endif %}

{% endblock %}

templates/administracion/panel.html
{% extends "base.html" %}
{% block content %}
<style>
	.container .row h1,p {color: #fff;}
</style>
	<div class="container">
		<div class="row">
			{% if panel %}
			<div class="col-md-4 col-sm-6 btn btn-lg btn-primary">
				<a href="{% url 'servicio:gestion' %}">
					<h1 class="text-center"><i class="fa fa-plane" aria-hidden="true"></i></h1>
					<p class="text-center">Viajes</p>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 btn btn-lg btn-success">
				<a href="{% url 'administracion:listar' %}">
					<h1 class="text-center"><i class="fa fa-address-card-o" aria-hidden="true"></i></h1>
					<p class="text-center">Empleados</p>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 btn btn-lg btn-warning">
				<a href="{% url 'administracion:reportes' %}">
					<h1 class="text-center"><i class="fa fa-area-chart" aria-hidden="true"></i></h1>
					<p class="text-center">Reportes</p>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 btn btn-lg btn-danger">
				<a href="{% url 'chofer:listar' %}">
					<h1 class="text-center"><i class="fa fa-taxi" aria-hidden="true"></i></h1>
					<p class="text-center">Choferes</p>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 btn btn-lg btn-info">
				<a href="{% url 'cliente:listar' %}">
					<h1 class="text-center"><i class="fa fa-user" aria-hidden="true"></i></h1>
					<p class="text-center">Clientes</p>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 btn btn-lg btn-primary">
				<a href="#">
					<h1 class="text-center"><i class="fa fa-btc" aria-hidden="true"></i></h1>
					<p class="text-center">Nomina(Coming Soon)</p>
				</a>
			</div>
			<div style="width: 100%; margin: 20px 0"></div>
			{% if bandera_chofer == True %}
				<div class="col-md-6">
					<div class="alert alert-dismissible alert-danger">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<h4 class="alert-heading">Notificacion de choferes <i class="fa fa-taxi" aria-hidden="true"></i></h4>
						<p class="mb-0">
							Hay choferes nuevos para por revisar.
							<a href="#" class="alert-link">¡Hazlo desde aqui!</a>.
						</p>
					</div>
				</div>
			{% endif %}
			<div class="col-md-6">
				<div class="alert alert-dismissible alert-primary">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<h4 class="alert-heading">Notificacion viajes</h4>
					<p class="mb-0">
						Hay viajes Pendientes por revisar
						<a href="#" class="alert-link">¡Haz clic aqui para verlos¡</a>.
					</p>
				</div>
			</div>
			{% else %}
			<div class="col-md-12">
			    <h2 class="text-center text-primary">No tiene permisos necesarios para acceder a este enlace</h2>
			    <h1 style="font-size: 110px"><i class="fa fa-chain-broken" aria-hidden="true"></i></h1>
			    <a href="{% url 'home:index' %}" class="btn btn-primary btn-lg text-center" style="display: block">Volver a la pagina principal</a>
			</div>
			{% endif %}
		</div>
	</div>
{% endblock content %}

templates/administracion/perfil.html
{% extends 'base.html' %}

 
{% block content %}
{% if empleado %}
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<img style="height: 80%; width: 100%; display: block; margin-left: auto; margin-right: auto; border-radius: 10px; margin-bottom: 10px;" src="/static/media/{{ empleado.foto }}" alt="Foto de {{ empleado.usuario.first_name }}" class="img-responsive">
			<h4>{{ empleado.usuario.first_name }} {{ empleado.usuario.last_name }}</h4>
			<h4 class="text-muted">{{empleado.usuario.username}}</h4>
		</div>
		<div class="col-md-9">
			<h3 class="text-center">Resumen de viajes</h3>
			<hr>
			<div class="row">
				<div class="col-md-6 form-control">
					<h4>Viajes Totales</h4>
					<h2 class="text-center text-primary">15</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Viajes Cancelados</h4>
					<h2 class="text-center text-danger">7</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Viajes Realizados</h4>
					<h2 class="text-center text-success">2</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Viajes Pendientes</h4>
					<h2 class="text-center text-warning">6</h2>
				</div>
			</div>
		</div>
	</div>
</div>
<br>
<div class="container">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-9">
			<br>
			<h3 class="text-center">Resumen de Clientes</h3>
			<hr>
			<div class="row">
				<div class="col-md-6 form-control">
					<h4>Operaciones con clientes</h4>
					<h2 class="text-center text-primary">15</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Clientes Registrados</h4>
					<h2 class="text-center text-danger">7</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Clientes Eliminados</h4>
					<h2 class="text-center text-success">2</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Clientes Suspendidos/Habilitado</h4>
					<h2 class="text-center text-warning">6</h2>
				</div>
			</div>
		</div>
<br>
		<div class="col-md-3"></div>
		<div class="col-md-9">
			<br>
			<h3 class="text-center">Resumen de Choferes</h3>
			<hr>
			<div class="row">
				<div class="col-md-6 form-control">
					<h4>Operaciones con Choferes</h4>
					<h2 class="text-center text-primary">15</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Choferes Registrados</h4>
					<h2 class="text-center text-danger">7</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Choferes Eliminados</h4>
					<h2 class="text-center text-success">2</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Choferes Suspendidos/Habilitado</h4>
					<h2 class="text-center text-warning">6</h2>
				</div>
			</div>
		</div>
<br>
		<div class="col-md-3"></div>
		<div class="col-md-9">
			<br>
			<h3 class="text-center">Resumen de Empleados</h3>
			<hr>
			<div class="row">
				<div class="col-md-6 form-control">
					<h4>Operaciones con Empleados</h4>
					<h2 class="text-center text-primary">15</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Empleados Registrados</h4>
					<h2 class="text-center text-danger">7</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Empleados Eliminados</h4>
					<h2 class="text-center text-success">2</h2>
				</div>
				<div class="col-md-6 form-control">
					<h4>Empleados Suspendidos/Habilitado</h4>
					<h2 class="text-center text-warning">6</h2>
				</div>
			</div>
		</div>
		<div class="col-md-3"></div>
		<br>
		<div class="col-md-9">
			<div class="row">
				<div class="col-md-12">
					<br><br>
					<h2 class="text-center text-primary" style="margin-bottom: 20px;">Datos del Empleado</h2>
					<div class="row">
						<div class="col-md-6">
							<p><strong>Cedula:</strong> V-{{ empleado.cedula }}</p>
							<p><strong>Nombre:</strong> {{ empleado.usuario.first_name }} {{ empleado.usuario.last_name }}</p>
							<p><strong>Email:</strong> {{ empleado.usuario.email }}</p>
							<p><strong>Dirección:</strong> {{ empleado.direccion }}</p>
							{% if empleado.rol == 'Administrador' %}
							<p><strong>Rol:</strong> Administrador <i class="fa fa-steam text-warning" aria-hidden="true"></i></p>
							{% else %}
							<p><strong>Rol:</strong> Empleado <i class="fa fa-id-card text-warning" aria-hidden="true"></i></p>
							{% endif %}
						</div>
						<div class="col-md-6">
							<p><strong>Telefono:</strong> {{ empleado.telefono }}</p>
							<p><strong>Sueldo:</strong> {{ empleado.sueldo }}</p>
							<p><strong>Fecha de nacimiento:</strong> {{ empleado.fecha_nacimiento }}</p>
							<p><strong>Fecha de Ingreso:</strong> {{ empleado.usuario.date_joined }}</p>
							<a href="{% url 'administracion:editar' empleado.id %}" class="btn btn-primary" style="right: 0">Editar Perfil</a>
						</div>
					</div>
					<p class="text-center" style="margin-top: 10px">Última Sesión: {{ empleado.usuario.last_login }}</p>
				</div>

			</div>
		</div>
	</div>

</div>
{% else %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
			    <h2 class="text-center text-primary">El empleado al que intenta acceder no esta disponible o no tiene los permisos necesarios para acceder</h2>
			    <h1 class="text-center text-primary" style="font-size: 110px"><i class="fa fa-chain-broken" aria-hidden="true"></i></h1>
			</div>
			<div class="col-md-12">
			    <a href="{% url 'home:index' %}" class="btn btn-primary btn-lg" style="display: block">Volver a la pagina principal</a>
			</div>
		</div>
	</div>
	{% endif %}

{% endblock content %}